### ISSUE TITLE
Error on buy a gizmo

### ISSUE THREAD

**Issue by iPolish** [OvercastNetwork/ProjectAres#22]
Lobby log:
[14:48:41] [Server thread/ERROR]: [API] Exception dispatching command from xPolish_ from tc.oc.commons.core.commands.CommandFutureCallback@3e20fb63 created...
	at tc.oc.commons.core.util.SystemFutureCallback.<init>(Unknown Source:43)
	at tc.oc.commons.core.commands.CommandFutureCallback.<init>(Unknown Source:66)
	at tc.oc.commons.core.commands.CommandFutureCallback.onSuccess(Unknown Source:45)
	at tc.oc.commons.core.commands.CommandFutureCallback.onSuccess(Unknown Source:33)
	at tc.oc.lobby.bukkit.gizmos.GizmoUtils.purchaseGizmo(Unknown Source:93)
	at tc.oc.lobby.bukkit.gizmos.Gizmos.click(Unknown Source:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source:43)
	at java.lang.reflect.Method.invoke(Unknown Source:498)
	at org.bukkit.event.EventMethodExecutor.execute(Unknown Source:53)
	at org.bukkit.event.BoundEventHandler.callEvent(Unknown Source:48)
	at org.bukkit.event.SimpleEventBus.callEventHandler0(Unknown Source:109)
	at org.bukkit.event.SimpleEventBus.callEvent0(Unknown Source:72)
	at org.bukkit.event.SimpleEventBus.callEvent0(Unknown Source:53)
	at org.bukkit.event.SimpleEventBus.callEvent(Unknown Source:46)
	at org.bukkit.event.SimpleEventBus.callEvent(Unknown Source:21)
	at org.bukkit.plugin.SimplePluginManager.callEvent(Unknown Source:501)
	at net.minecraft.server.PlayerConnection.a(Unknown Source:2004)
	at net.minecraft.server.PacketPlayInWindowClick.a(Unknown Source:33)
	at net.minecraft.server.PacketPlayInWindowClick.a(Unknown Source:10)
	at net.minecraft.server.PlayerConnectionUtils$1.run(Unknown Source:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source:511)
	at java.util.concurrent.FutureTask.run(Unknown Source:266)
	at net.minecraft.server.SystemUtils.a(Unknown Source:46)
	at net.minecraft.server.MinecraftServer.processTasks(Unknown Source:1618)
	at net.minecraft.server.DedicatedServer.processTasks(Unknown Source:396)
	at net.minecraft.server.MinecraftServer.D(Unknown Source:808)
	at net.minecraft.server.DedicatedServer.D(Unknown Source:366)
	at net.minecraft.server.MinecraftServer.C(Unknown Source:764)
	at net.minecraft.server.MinecraftServer.runTick(Unknown Source:752)
	at net.minecraft.server.MinecraftServer.run(Unknown Source:667)
	at java.lang.Thread.run(Unknown Source:745)

tc.oc.api.exceptions.NotFound: Not found
	at tc.oc.api.http.HttpClient$RequestCallable.call(HttpClient.java:289) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
	at tc.oc.api.http.HttpClient$RequestCallable.<init>(HttpClient.java:237) ~[?:?]
	at tc.oc.api.http.HttpClient.request(HttpClient.java:196) ~[?:?]
	at tc.oc.api.http.HttpClient.request(HttpClient.java:161) ~[?:?]
	at tc.oc.api.http.HttpClient.post(HttpClient.java:133) ~[?:?]
	at tc.oc.api.ocn.OCNUserService.purchaseGizmo(OCNUserService.java:91) ~[?:?]
	at tc.oc.lobby.bukkit.gizmos.GizmoUtils.purchaseGizmo(GizmoUtils.java:92) ~[?:?]
	at tc.oc.lobby.bukkit.gizmos.Gizmos.click(Gizmos.java:78) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.event.EventMethodExecutor.execute(EventMethodExecutor.java:53) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.BoundEventHandler.callEvent(BoundEventHandler.java:48) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.SimpleEventBus.callEventHandler0(SimpleEventBus.java:109) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.SimpleEventBus.callEvent0(SimpleEventBus.java:72) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.SimpleEventBus.callEvent0(SimpleEventBus.java:53) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.SimpleEventBus.callEvent(SimpleEventBus.java:46) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.event.SimpleEventBus.callEvent(SimpleEventBus.java:21) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:501) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.PlayerConnection.a(PlayerConnection.java:2004) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:33) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:10) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.PlayerConnectionUtils$1.run(SourceFile:13) ~[sportbukkit.jar:git-Bukkit-22a6a11]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.SystemUtils.a(SourceFile:46) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.MinecraftServer.processTasks(MinecraftServer.java:1618) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.DedicatedServer.processTasks(DedicatedServer.java:396) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:808) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:366) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:764) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.MinecraftServer.runTick(MinecraftServer.java:752) [sportbukkit.jar:git-Bukkit-22a6a11]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:667) [sportbukkit.jar:git-Bukkit-22a6a11]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

RoR Api Instance Log:

[PID 6205] Started POST "//users/_58a36c60acacf629e6000000/purchase_gizmo" for 37.59.140.109 at 2017-02-24 14:49:59 -0500
[PID 6205] Processing by Api::UsersController#purchase_gizmo as JSON
[PID 6205]   Parameters: {"gizmo_name"=>"chickenifier5000", "price"=>10000, "id"=>"_58a36c60acacf629e6000000", "user"=>{}}
[PID 6205] Completed 404 Not Found in 4ms (Views: 0.3ms)

**Comment by YukonAppleGeek** [comment]
Issues are not to be used for getting help with running the plugins, please read the readme https://github.com/OvercastNetwork/ProjectAres#getting-help.
